version: '3.4'

services:
  pokedex.web:
    image: ${DOCKER_REGISTRY-}pokedexweb
    build:
      context: .
      dockerfile: src/Pokedex.Web/Dockerfile
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: always
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    networks:
      - pokedex
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    networks:
      - pokedex
networks:
  pokedex:
    driver: bridge

volumes:
  elasticsearch-data: